### ISSUE TITLE
v2.0.19

### ISSUE THREAD

**Issue by Voles** [angular-ui-tree/angular-ui-tree#821] opened 2016-09-11 16:33 UTC
@jacobscarter I see there's v2.0.19 but that version does not contain any code changes. See https://github.com/angular-ui-tree/angular-ui-tree/compare/v2.18.0...v2.19.0 for the diff.

Can we remove this tag / version?

**Comment by jacobscarter** [comment] 2016-09-11 17:52
@Voles this happened because 2.18 was released with regressions and breaks, @StefanCodes rolled the repo back to 2.17 but bower still had 2.18, releasing 2.18 didn't overwrite the bad version bower had, so 2.19 was released.  So while GitHub shows no code difference between the two versions, if you pull them down from bower you will see the differences.  Because everything is working fine as is I would like to not complicate things more by trying to roll things back to 2.18 and updating bower, npm, etc.  I'll close the ticket but let me know if you disagree.

I am looking forward to getting 2.20 released with the changes that have already been merged as well as PR #819 and #807 please let me know if getting those merged is something we can do sooner rather than later.

I don't want to lose our momentum we have built up.

**Closed by jacobscarter** 2016-09-11 17:52 UTC

**Comment by Voles** [comment] 2016-09-11 18:55
@jacobscarter perfect, thanks for your clarification. I'll take a look at the outstanding PR's.

**Comment by jacobscarter** [comment] 2016-09-11 18:55
@Voles you're the man! Thank you.
