### ISSUE TITLE
Exception with angular 1.3.8 , ui-tree  2.1.5 , IE11

### ISSUE THREAD

**Issue by varadero** [angular-ui-tree/angular-ui-tree#318] opened 2015-01-05 19:33 UTC
An exception is thrown when I'm trying to use your demo at https://github.com/JimLiu/angular-ui-tree/tree/master/demo with current latest versions of angular (1.3.8) and ui-tree (2.1.5) (using Visual Studio 2013 with Internet Explorer 11 as a debug target)

```
Unhandled exception at line 3066, column 13 in http://localhost:27517/angular.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'contains'
```

The line 3066 in angular.js version 1.3.8 is:

```
if (!related || (related !== target && !target.contains(related))) {
```

This happens when i click (and eventually try to drag) any of the tree nodes.

It turns out that if I configure $compileProvider in the following way, the problem disappears:

```
angular.module("app").config(['$compileProvider', function ($compileProvider) {
        $compileProvider.debugInfoEnabled(false);
    }]);
```

Here you can find example (open it with Internet Explorer 11) - unfortunately I cannot reproduce this error every time using Plunker, but it happens always when I use Visual Studio and IE11 and most often when you open developer tools of IE11 and refresh the page (without using Visual Studio).

http://plnkr.co/edit/tLM0YhlXmPNPmq5ZD6lW?p=preview

Just try to drag some of the nodes - IE11 will (eventually) stop on the line 3066 in angular.js.

This is a screenshot of what happens - in the "Watches" window the "target" variable is expanded - it seems that it contains the document element, which don't have "contains" method:

![angular-ui-tree-ie11-exception](https://cloud.githubusercontent.com/assets/7610713/5618341/b146af12-9520-11e4-8168-bd094798510a.jpg)
:

**Comment by varadero** [comment] 2015-01-06 08:15
The same issue is reported earlier:

https://github.com/JimLiu/angular-ui-tree/issues/298

**Comment by Mouvedia** [comment] 2015-06-08 08:45
Is this a dupe of #10259?

**Comment by jacobscarter** [comment] 2016-09-11 07:02
Closing this issue due to inactivity. See #815 for more information.
Please create a new issue is this still occurs with the current version of the component.

**Closed by jacobscarter** 2016-09-11 07:02 UTC
