### ISSUE TITLE
Drag And Drop not working 

### ISSUE THREAD

**Issue by Prateek479** [angular-ui-tree/angular-ui-tree#629] opened 2015-10-20 13:43 UTC
integrated the library as mentioned in the demo . View is perfectly fine but, on click of the ui-tree-node or ui-tree-handle , it disappear from the mark with an error :
TypeError: Cannot read property 'createDocumentFragment' of null

attaching a screen shot for reference . I am including jquery as well on my page (I hope that wont be an issue).
<img width="1270" alt="screen shot 2015-10-20 at 7 09 25 pm" src="https://cloud.githubusercontent.com/assets/3468712/10608839/786bfeec-775e-11e5-99f1-1992c34be6cc.png">

**Comment by icfantv** [comment] 2015-10-21 23:25
I just upgraded from 2.5 to 2.10 and am seeing this as well.  I have yet to debug why or try interim versions to see which one introduced it.

**Comment by icfantv** [comment] 2015-10-22 17:40
In our case, we're using the full version of jQuery so I've updated that to 2.1.4 from 2.1.1 and we're getting a new error message `Cannot read property '$id' of null` on line 1205 of `angular-ui-tree.js`.  investigating further.

**Comment by Voles** [comment] 2015-11-14 13:37
@Prateek479 what version of jQuery, Angular and angular-ui-tree are you using? Is it possible to reproduce the errors in a jsFiddle?

**Comment by icfantv** [comment] 2015-11-14 20:42
@Voles - sadly, no.  It started to become a massive time sink so I had to give up and go back to 2.5.

**Comment by IdanCo** [comment] 2015-11-29 15:16
I too reverted to 2.5 and issue was solved

**Comment by Prateek479** [comment] 2015-11-29 20:08
@Voles    "jquery":  "2.1.4" and "angular-ui-tree": "~2.10.0" is the version , I will reproduce the error on fiddle and will share the link for same :)

**Comment by blemoine** [comment] 2015-12-01 08:06
I've had the same problem, and the root cause was that I was attaching my angular application to the document.
```angular.bootstrap(document, ['venom'], {strictDi:true});```

A simple fix for this was to attach the angular application to the body :
```angular.bootstrap(document.getElementsByTagName('body')[0], ['venom'], {strictDi:true});```

The problem is probably using $rootElement to append the helper.

**Comment by IdanCo** [comment] 2016-02-17 14:07
Does anyone have a clue about this one?

**Comment by IdanCo** [comment] 2016-02-17 14:36
ok, that was easy -
just changed
```$rootElement.append(dragElm);```
to
```$document.find('body').append(dragElm);```
I'll create a PR ASAP

**Comment by alamoot** [comment] 2016-02-17 15:29
Thank you @blemoine your solution fixed my error.
Had the exact same error with JQuery 2.2 and angular ui.tree 2.14.0

**Comment by jet-snowman** [comment] 2016-02-26 22:33
ASAP ? 9 days were gone!

**Comment by IdanCo** [comment] 2016-03-01 21:53
@jet-snowman , I wrote the exact line of code that needs changing, if it was so urgent you could easily create your own PR. If you're not sure how i'll be happy to show you.

anyway, PR #729 was created.

**Comment by pedrommuller** [comment] 2016-05-17 14:16
I had the same issue that @alamoot  also had, so I decided to apply @blemoine approach and it's working like a charm, any other alternatives to fix it?

I'm using angular 1.5, jquery 2.2.3 and 2.15.0

**Comment by jacobscarter** [comment] 2016-09-11 08:14
This is in 2.19.0

**Closed by jacobscarter** 2016-09-11 08:14 UTC

**Comment by Sanghamitranew** [comment] 2017-10-27 08:34
@Prateek479 have you solved the issue? I am still unable to create new parent node.I am using  angular 1 and it angular-ui-tree.Please help me.
![screenshot](https://user-images.githubusercontent.com/33146820/32095134-c3bdb118-bb1f-11e7-93da-c62d29bbd3b7.png)
