### ISSUE TITLE
How to fix a flickering effect when dragging onto an empty placeholder?

### ISSUE THREAD

**Issue by oozywaters** [angular-ui-tree/angular-ui-tree#630] opened 2015-10-22 02:53 UTC
Hi,

As I mentioned in my question, when I start dragging a node onto an empty tree, its placeholder starts flickering and it's difficult to add a new node.

You can see such behaviour on the [demo page] (http://angular-ui-tree.github.io/angular-ui-tree/#/connected-trees) ("Connected trees" example)

Is there any way/workaround to fix this issue?

**Comment by SvenJunga** [comment] 2015-10-23 20:00
Hi

I don't see any flickering at the connected trees example. What's your setup? (device, OS, browser)

**Comment by oozywaters** [comment] 2015-10-24 08:41
MacBook Pro 13, Yosemite 10.10.5.

I've tested this example with Chrome and Safari and had the same result. I've attached the gif to demonstrate the problem. It actually flickers very fast while moving mouse over it (the gif example doesn't show that because of frame rate limit).

![ui-tree](https://cloud.githubusercontent.com/assets/6844772/10709674/c815a274-7a72-11e5-8e74-748c643b01f0.gif)

**Comment by SvenJunga** [comment] 2015-10-24 11:24
~~Can't reproduce this with almost the same device but El Capitan. Anyone else with Yosemite installed?~~
OK, got it. This happens here too when the node is dragged over the lower area of the dropping zone. Even happens on iPhone. Without looking into the code I think this should happen on any device, no matter what browser. I assume that everytime you move the selected node inside dropping zone of tree 1 but outside one node height it checks whether the empty dropping zone or the placeholder should be displayed. Can't look any further into this one since I'll be on vacation for one week. Somebody feel free! :)

**Comment by oozywaters** [comment] 2015-10-25 05:03
@SvenJunga thanks!

**Comment by Voles** [comment] 2015-11-04 22:14
@SvenJunga thanks for looking into this! How does the div you add on top prevent the flickering? I assume that div is still able to receive the node being moved around?

**Comment by arthurfabre** [comment] 2015-12-02 11:04
I think I've figured this out.

The problem is that when an element is dragged onto the empty placeholder, the element is added to the tree using [`targetNode.place(placeElm)`](https://github.com/angular-ui-tree/angular-ui-tree/blob/master/source/directives/uiTreeNode.js#L377).
This [removes the empty placeholder](https://github.com/angular-ui-tree/angular-ui-tree/blob/master/source/controllers/treeCtrl.js#L32).
Once there is no placeholder, the ui-tree div has no visible children, so it's height collapses to 0.
Next time the dragged element is moved, getting the DOM element it's being dragged above doesn't return the ui-tree div, but rather whatever happens to be there.

An easy fix for this is to set the height of ui-tree div explicitly. In my case setting the height to 100% as follows works:

    .angular-ui-tree {
      height: 100%;
    }

**Comment by joujo1212** [comment] 2016-02-29 15:23
I fixed this issue with flickering, but I have another problem, see GIF in link ..when I'm dragging item from right list without stop moving, item is not possible to add to left list. Why? From UX it's really bad, I think

https://www.dropbox.com/s/xr4uxinh4qxk3ra/angular%20ui%20tree%20view%20bug.gif?dl=0

**Comment by SvenJunga** [comment] 2016-02-29 15:30
@joujo1212 see this issue #562

**Comment by joujo1212** [comment] 2016-02-29 15:38
Thanks a lot @SvenJunga , it helped!! i didn't see this issue, sorry.

**Comment by jacobscarter** [comment] 2016-09-11 08:16
Closing this issue due to inactivity. See #815 for more information.
Please create a new issue is this still occurs with the current version of the component.

**Closed by jacobscarter** 2016-09-11 08:16 UTC
