### ISSUE TITLE
Page doesn't scroll when dragging a node in IE11

### ISSUE THREAD

**Issue by ernestopye** [angular-ui-tree/angular-ui-tree#544] opened 2015-08-06 18:31 UTC
I replicated this by going into the demo page and adding a bunch of nodes (alternatively, you can just resize the window so that not all of the tree is visible). If you then try to drag the top node to the bottom to try to force it to scroll, you lose your selection and it cancels the drag. Seems to work as expected in Chrome and Firefox.

Let me know if I can provide any further details on this, but I'm hoping it's simple enough to replicate this, and possible to work around.

Thanks for your work on this component, it's incredibly appreciated!

**Comment by AndrewIsh** [comment] 2015-10-05 15:10
This appears to be a duplicate of #158. I am experiencing the same problem and have created [a plunker](https://github.com/angular-ui-tree/angular-ui-tree/issues/158) to demonstrate. Is there any chance someone could take a look at this as it's quite a problem for IE users with big trees! Thanks :)

**Comment by jacobscarter** [comment] 2016-09-11 07:55
Closing this issue due to inactivity. See #815 for more information.
Please create a new issue is this still occurs with the current version of the component.

**Closed by jacobscarter** 2016-09-11 07:55 UTC

**Comment by jacobscarter** [comment] 2016-09-12 16:24
Available in v2.21.1
