### ISSUE TITLE
Increasing Drop Area of a Tree

### ISSUE THREAD

**Issue by vangk** [angular-ui-tree/angular-ui-tree#600] opened 2015-09-29 15:29 UTC
I was wondering if it is possible to increase the dropping area when dragging one node from a tree into another tree if it already has an existing node.

For example, there are 2 trees, both horizontal layouts. Tree 1 has nodes and Tree 2 is empty. Tree 2 has an empty placeholder (dropping area) where you can drop nodes from another tree. You drag a node from Tree 1 into the empty placeholder area which works fine, but then if you try to drag another node from Tree 1 into tree 2, it will only accept a node if you drag the node right next to the first node that was dropped.

I'm basically wondering if you can create a drop area for another tree to accept nodes where you can keep dragging and dropping into without being restricted to dragging and dropping right next to an existing node.

Any help will be appreciated! Thanks!

**Comment by TonyNguyen101** [comment] 2015-09-29 17:33
Oh yes, I would love to hear anyone’s thoughts on this too.

Tony

**Comment by vaz9** [comment] 2015-09-30 01:06
wrapper ::before, ::after ???
or dynamically 'helpers' block's if drag items made of tree.
We drag a node from Tree 1, then the second tree is invisible blocks related to the last node. but I think this solution is best suited for wrapping or the first and last node =\
sorry for my bad English

**Comment by vangk** [comment] 2015-10-01 15:36
I'm not sure if I understand what you mean. Could you provide a demo?

**Comment by giladv** [comment] 2015-11-26 04:06
i"m new to ui-tree but i've noticed using margin instead of padding for indentation of ul's causes better interaction in general

**Comment by jacobscarter** [comment] 2016-09-11 08:09
closing because duplicate of #465

**Closed by jacobscarter** 2016-09-11 08:09 UTC
Labels: duplicate
