### ISSUE TITLE
Error: treeNodesCtrl.scope.$modelValue is undefined (Version 2.5.0)

### ISSUE THREAD

**Issue by ColtsBR** [angular-ui-tree/angular-ui-tree#497] opened 2015-06-29 19:44 UTC
I'm getting the following error in my application. Looking for some direction:

Error: treeNodesCtrl.scope.$modelValue is undefined
$scope.init@http://localhost/Website/Content/plugins/angular-ui-tree/angular-ui-tree.js:68:11
.link@http://localhost/Website/Content/plugins/angular-ui-tree/angular-ui-tree.js:561:13
invokeLinkFn@http://localhost/Website/Scripts/libraries/angular/angular.d.js:8219:9
nodeLinkFn@http://localhost/Website/Scripts/libraries/angular/angular.d.js:7729:1
compositeLinkFn@http://localhost/Website/Scripts/libraries/angular/angular.d.js:7078:13
publicLinkFn@http://localhost/Website/Scripts/libraries/angular/angular.d.js:6957:30
createBoundTranscludeFn/boundTranscludeFn@http://localhost/Website/Scripts/libraries/angular/angular.d.js:7096:1
controllersBoundTransclude@http://localhost/Website/Scripts/libraries/angular/angular.d.js:7756:18
ngRepeatAction@http://localhost/Website/Scripts/libraries/angular/angular.d.js:24553:15
$watchCollectionAction@http://localhost/Website/Scripts/libraries/angular/angular.d.js:14108:13
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost/Website/Scripts/libraries/angular/angular.d.js:14243:23
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost/Website/Scripts/libraries/angular/angular.d.js:14506:13
bootstrapApply@http://localhost/Website/Scripts/libraries/angular/angular.d.js:1448:9
invoke@http://localhost/Website/Scripts/libraries/angular/angular.d.js:4185:14
bootstrap/doBootstrap@http://localhost/Website/Scripts/libraries/angular/angular.d.js:1446:1
bootstrap@http://localhost/Website/Scripts/libraries/angular/angular.d.js:1466:1
angularInit@http://localhost/Website/Scripts/libraries/angular/angular.d.js:1360:5
@http://localhost/Website/Scripts/libraries/angular/angular.d.js:26176:5
trigger@http://localhost/Website/Scripts/libraries/angular/angular.d.js:2744:7
createEventHandler/eventHandler@http://localhost/Website/Scripts/libraries/angular/angular.d.js:3014:9

<div ng-repeat="Attribute in attributes" ui-tree-node="" class="list-group-item list-group-item-inverse ng-scope angular-ui-tree-node">

The ng-repeats work as expected and the display is fine in the app, but none of the tree functionality is working. 

Code Snippets:
https://gist.github.com/ColtsBR/ce916dcdb5c3fe3a95b1

**Comment by burakkilic** [comment] 2015-07-02 17:20
+1

**Comment by avvett** [comment] 2015-07-12 17:59
+1

**Comment by kennyw728** [comment] 2015-10-30 23:05
+1. I have also run into this issue.

**Comment by marsanla** [comment] 2015-11-17 15:17
+1

**Comment by JinZenDigital** [comment] 2015-11-17 19:08
+1

**Comment by i-am-dror** [comment] 2015-11-29 10:06
+1

**Comment by Voles** [comment] 2015-11-29 17:22
This should have been fixed in v2.10.0. The latest release is v2.11.0. Can you please update and confirm if the issue is resolved? Thanks!

**Comment by i-am-dror** [comment] 2015-11-30 07:25
I'm using v2.11.0

**Comment by mojogitoverhere** [comment] 2016-03-24 03:23
Can you update the atmosphere repo? Seems like the latest version over there is 2.6.0_1.

**Comment by jacobscarter** [comment] 2016-09-11 07:48
This should be fixed with 2.19.0

**Closed by jacobscarter** 2016-09-11 07:48 UTC
