### ISSUE TITLE
Can't drop a node inside empty node

### ISSUE THREAD

**Issue by nishantsamant** [angular-ui-tree/angular-ui-tree#692] opened 2016-01-06 08:56 UTC
I am not able to drop a node inside an empty Node? Is this an existing issue?

**Comment by zachlysobey** [comment] 2016-01-06 17:13
You posted in the existing issue #688 2 hours prior to posting this one...

**Comment by Voles** [comment] 2016-01-06 20:51
Duplicate of #688

**Closed by Voles** 2016-01-06 20:51 UTC
