### ISSUE TITLE
drag and drop broken (within tree)

### ISSUE THREAD

**Issue by rlintern** [angular-ui-tree/angular-ui-tree#831] opened 2016-09-16 22:25 UTC
*Note*: for support questions, please use our [Gitter channel](https://gitter.im/angular-ui-tree/angular-ui-tree). This repository's issues are reserved for feature requests and bug reports.

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Cannot move nodes around in the tree in the latest build (2.22.0).  Our application and   https://angular-ui-tree.github.io/angular-ui-tree/#/basic-example are both broken.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar.**

**What is the expected behavior?**
You can move nodes around easily and freely.

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, UI Tree and which browser / OS are affected by this issue? Did this work in previous versions of Angular, UI Tree? Please also test with the latest version.**
Previous build 2.21.3 works, but latest build 2.22.0 doesn't work
Same behaviour for myself and another co-worker, in Chrome and FireFox (windows)

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by riyunoa** [comment] 2016-09-20 02:08
I have the same issue as of updating to 2.22.0. I'm also using 2.21.3, it works.

**Comment by jacobscarter** [comment] 2016-09-20 02:16
@riyunoa that makes it easier thanks. So 2.21.3 is working and 2.22.0 breaks?

**Comment by jacobscarter** [comment] 2016-09-20 05:56
@Voles @StefanCodes this is the change I made that caused the break above, this change is what fixed the issue where you couldn't drag horizontally from one tree to another, I am hoping we don't have to roll back the change, I am looking into it but another pair of eyes would be nice, let me know if you see the problem.

https://github.com/angular-ui-tree/angular-ui-tree/commit/d3796367fcbdbf7270bf01210bae9e3b4f7c80ab

**Comment by jacobscarter** [comment] 2016-09-20 06:54
Fixed with PR #834

**Comment by jacobscarter** [comment] 2016-09-21 05:41
Fixed in version 2.22.1

**Closed by jacobscarter** 2016-09-21 05:41 UTC

**Comment by tinybright** [comment] 2016-09-23 03:20
It hasn't been fixed in v2.22.1.
if you drag a handle and release it,it will keep in draging status.

**Comment by jacobscarter** [comment] 2016-09-23 03:30
@tinybright I cannot reproduce this:

Which versions of Angular and which browser / OS are you using?

**Comment by tinybright** [comment] 2016-09-23 03:33
@jacobscarter  Angular 1.5.6. Chrome 50.0.2661.102 m

**Comment by tinybright** [comment] 2016-09-23 03:52
@jacobscarter I made a mistake.My problem is same as issue 830.Not this one.
