### ISSUE TITLE
Controller 'uiTree', required by directive 'uiTreeNodes', can't be found!

### ISSUE THREAD

**Issue by takeit** [angular-ui-tree/angular-ui-tree#308] opened 2014-12-12 15:30 UTC
Hi,

I checked other issues related to this problem here but it doesnt solve my problem. I try to achive something like here: http://jsfiddle.net/jimliu/4924U/5/

I do:

```
<div ui-tree="treeOptions" id="tree-root">
         <ol ui-tree-nodes="" ng-model="data">
                <li ng-repeat="node in data" ui-tree-node">
                        {{ node.name }}
                        <ol ui-tree-nodes="" ng-model="node.__children" ng-class="{hidden: !collapsed}">
                               <li ng-repeat="node in node.__children" ui-tree-node>
                                          {{ node.title }}
                              </li>
                        </ol>
                </li>
          </ol>
</div>
```
but I get this error all the time: `Controller 'uiTree', required by directive 'uiTreeNodes', can't be found!`.
The first level of the tree displays properly but when displaying `__children`, it fails...

I use:
- Angular UI Tree v2.1.5
- AngularJS v1.2.15

Would be nice to get some hints how to fix it.

**Comment by clai1018** [comment] 2015-02-11 20:31
I'm running into this problem as well. Did you find a fix?

**Comment by takeit** [comment] 2015-02-11 20:59
@clai1018 I based it on template where html looks like:

```html
<div ui-tree="treeOptions" id="tree-root">
    <ol ui-tree-nodes ng-model="data">
        <li ng-repeat="node in data" ui-tree-node ng-include="'nodes_renderer.html'">
        </li>
     </ol>
</div>
```

and template is:
```js
<script type="text/ng-template" id="nodes_renderer.html">
    <div ui-tree-handle class="tree-node tree-node-content angular-ui-tree-handle">
    {{ node.title  }}
    </div>
    <ol ui-tree-nodes ng-model="node.__children">
         <li ng-repeat="node in node.__children" ui-tree-node ng-include="'nodes_renderer.html'"></li>
    </ol>
</script>
```

I use:
- Angular UI Tree v2.1.5
- AngularJS 1.3.7

It works just fine.

**Comment by clai1018** [comment] 2015-02-11 21:46
Thanks a lot for responding! So what did you change from your previous code when you were getting the error?

**Comment by clai1018** [comment] 2015-02-11 23:14
I fixed it as well. Thanks again!

**Comment by hstarorg** [comment] 2015-04-11 03:03
@clai1018  Would you share your solution,thanks.

**Comment by leroyxiao** [comment] 2015-04-28 18:34
@clai1018 and @takeit Could you post your solution ? Thanks

**Comment by stripathix** [comment] 2015-09-03 14:49
I am also getting same error. Can you please tell me what was the solution for this?
Angular ui-tree : 2.2.0

**Comment by w0lph** [comment] 2015-10-28 11:44
I just love when people fix things and don't post the solution. "I fixed it as well" is so relevant...

**Comment by itanex** [comment] 2015-12-22 07:25
This is caused by NG-INCLUDE resolving the provided path/id in error. 

1) The URI resulted in and HTTP Error (404, 500, etc)
** Solve by fixing URI request issue
2) The provided script tag ID was not found
** Solve by making sure the script tag ID you wish to use is actually rendered into the page

In some cases with the URI you may need to resolve the path provided through the $sce service. For more information [read up on that service](https://docs.angularjs.org/api/ng/service/$sce)

**Comment by derek-adair** [comment] 2016-06-15 08:57
Is this still an issue in 2.16?

**Comment by jacobscarter** [comment] 2016-09-11 06:59
Closing this issue due to inactivity. See #815 for more information.
Please create a new issue is this still occurs with the current version of the component.

**Closed by jacobscarter** 2016-09-11 06:59 UTC
