### ISSUE TITLE
Possible bug on reordering?

### ISSUE THREAD

**Issue by egtavares** [angular-ui-tree/angular-ui-tree#832] opened 2016-09-19 13:13 UTC
I cannot make a list that can be reordered with dragging and dropping within it.
Te example at  http://angular-ui-tree.github.io/angular-ui-tree/#/table-example doesn't seem to work too. I tried using Chrome, Firefox, IE and MS Edge and was not able to reorder that online example. Is this a bug?

**Comment by egtavares** [comment] 2016-09-19 19:20
Searching the web, I stumbled upon a tip to use version 2.16.0 (I was using 2.20) for another issue. I installed version 2.16.0 and my code now works correctly. So it really seems to be a bug

**Comment by jacobscarter** [comment] 2016-09-19 20:08
Note: Appears to be a problem with the recognition of *vertical* movement

**Comment by jacobscarter** [comment] 2016-09-20 04:58
Duplicate of #831 please follow progress there.

**Closed by jacobscarter** 2016-09-20 04:58 UTC
Labels: bug, duplicate, reviewed
