### ISSUE TITLE
Scroll when dragging a node on a large tree.

### ISSUE THREAD

**Issue by dowanx** [angular-ui-tree/angular-ui-tree#644] opened 2015-11-11 00:57 UTC
I love the angular-ui-tree module and use it often within the web apps I am building, but I have ran into a small UX issue.

The issue shows itself when a tree is long and a user is trying to drag a node from the top of the tree to the very bottom of the tree.  A user will have to pick up a node, drop it at the bottom of the screen, scroll down, pick it back up and rinse repeat until they get to the end of the tree.  A savvy user will pick it up and then use the mouse wheel to scroll down, but lets face it not very many users are savvy ;p

I looked at the code and it doesn't seem to take this into consideration.  Is this the correct place to put a request for this functionality?  I would actually love to help develop this functionality, but I am not sure where to start as I am pretty new to github.

**Comment by AndrewIsh** [comment] 2016-02-03 10:39
This appears to be a duplicate of #158 and #544. I really wish this issue would be addressed :(

**Comment by Voles** [comment] 2016-09-12 06:55
This should be fixed with #814 which has been merged just now

**Comment by jacobscarter** [comment] 2016-09-12 16:23
Available in 2.21.1

**Closed by jacobscarter** 2016-09-12 16:23 UTC
Labels: bug
