### ISSUE TITLE
Sometimes dropping doesn't work

### ISSUE THREAD

**Issue by DanieleRatti** [angular-ui-tree/angular-ui-tree#798] opened 2016-07-31 09:45 UTC
I noticed that sometimes, even if accept, dragStart and dragStop events are called and return true, the "dropped" event is not called and the drag'n'drop does not succeed.

Does anyone know this issue?

Update: I just discovered that it happens when I try to move an item under another item with a huge height (see the attachment). It's caused by the variable outOfBounds which seems true when I release the item even if the drop placeholder is shown and the position is correct!

I changed the line 1076 to:
`if (allowDrop !== false && scope.$$allowNodeDrop /*&& !outOfBounds*/)`
but it's not correct.

<img width="836" alt="x" src="https://cloud.githubusercontent.com/assets/1781218/17275874/6b5bcda6-5717-11e6-8e04-cdb2792e2a82.png">

**Comment by sebek64** [comment] 2016-09-06 14:02
I've discovered the same error. For me, the problem is the following sequence of steps:

1. accept is called - returns true
2. accept is called - returns false
3. beforeDrop is called, returns a promise
4. even when the promise succeeds, dropped is not called

The problem is with outOfBounds variable, which is assigned true in the "else" branch.

**Comment by dturing** [comment] 2016-09-22 15:46
i suspect this might be #763. 
@DanieleRatti is your drop maybe on a child of ui-tree-node, which itself doesnt fit the check  in [uiTreeNode.js#L444](https://github.com/angular-ui-tree/angular-ui-tree/blob/master/source/directives/uiTreeNode.js#L444)?

**Comment by Voles** [comment] 2016-12-20 22:20
#856 removed the outOfBounds variable and has been merged. See the latest release, v2.22.2

**Closed by Voles** 2016-12-20 22:20 UTC
Labels: bug, reviewed
